### ISSUE TITLE
关于GitHub Action CI测试的几个建议

### ISSUE THREAD

**Issue by EldersJavas** [AOF-Dev/MCinaBox#932]
<b>首先,非常感谢这个项目.</b>

 ### 在查看`Action`后,我提出以下几点建议:

1.  在激活`Action`上添加更多条件,减少`Action`占用和不必要的运行

举个例子
```yml
  push:
    branches:
      - master
      - feature/*
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'

  pull_request:
    branches:
      - master
      - feature/*
      - release/*
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'
```

2. `Artifacts`能够添加更多对`Debug`更有帮助的日志
3. 添加更多系统环境和`Android SDK`包环境

      首先可以添加更多系统
      ```yml
           matrix:
              os: [ubuntu-latest, macos-latest, windows-latest]
          runs-on: ${{ matrix.os }}
      #由于各系统语法不同,估计这个项目不能直接这样写,应该分开写
      ```

还可以枚举修改`compileSdkVersion`,`buildToolsVersion`,`action`实现应该不能单靠一个`yml`文件.

4.  添加`appveyor`作为新测试环境,比`Action`强不少(主要是日志功能好太多)
5. 看起来好像`master写保护`没添加-必须过`CI`才能`merge`<del>(好像是看错了</del>

#### 以上所有的建议我都可以帮忙achieve,如有需要我会第一时间`Pull Request`.

最后,再次感谢开发者团队!
Thanks all the time.
